cracker: main.o getvalues.o numelim.o
	gcc main.o getvalues.o numelim.o -o cracker

main.o: main.c
	gcc -c main.c
	
getvalues.o: getvalues.c
	gcc -c getvalues.c
	
numelim.o: numelim.c
	gcc -c numelim.c
